on:
  workflow_call:
    inputs:
      prerelease:
        description: Marks the release as a pre-release
        type: boolean
        default: false
        required: false
name: "Build and upload release"
concurrency:
  group: ${{ github.workflow }}
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          repository: baerchen201/LethalModBuilder
          path: .
        name: "Checkout LethalModBuilder repository"
      - uses: actions/checkout@v6
        with:
          path: target
        name: "Checkout target repository"
      - run: bash build.sh
        name: "Build release file"
      - uses: softprops/action-gh-release@v3
        if: github.ref_type != 'tag'
        with:
          name: ${{ github.sha }}
          files: target/release.zip
          tag_name: v${{ github.run_number }}
          prerelease: ${{ inputs.prerelease }}
        name: "Upload release file (continuous release)"
      - uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          name: ${{ github.sha }}
          files: target/release.zip
          tag_name: ${{ github.ref_name }}
          prerelease: ${{ inputs.prerelease }}
        name: "Upload release file"
